# Home.py

import streamlit as st

st.set_page_config(
    page_title="Forecasters' Tools",
    page_icon="🗺️",
    layout="wide"
)

# Inject Custom CSS for the Blue Header Bar and Button Styling
st.markdown(
    """
    <style>
    /* CUSTOM BLUE HEADER BAR */
    .main-header {
        background-color: #1E90FF;
        color: white;
        padding: 10px 0;
        text-align: center;
        font-size: 28px;
        font-weight: bold;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        z-index: 1000;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    /* Push main content down to account for the fixed header */
    /* Note: These selectors might need adjustment depending on Streamlit's version, 
       but they aim to target the main content area for padding. */
    .st-emotion-cache-1g8i5u7, .st-emotion-cache-6qob1r, .st-emotion-cache-1y4pm5r {
        padding-top: 80px; 
    }
    
    .logout-link {
        position: absolute;
        right: 20px;
        top: 15px;
        font-size: 14px;
        color: white;
        text-decoration: none;
    }
    
    /* CUSTOM BUTTON STYLING for st.page_link buttons */
    /* We target the container of st.page_link which looks like a button */
    div.stPageLink {
        display: flex;
        justify-content: center;
        margin-bottom: 5px; 
    }
    div.stPageLink > a {
        /* This targets the <a> tag generated by st.page_link */
        width: 250px;
        height: 40px;
        margin: 5px 0;
        font-size: 16px;
        border: 1px solid #1E90FF; 
        color: #1E90FF;
        background-color: white;
        display: flex; /* Make the <a> a flex container */
        align-items: center; /* Center text vertically */
        justify-content: center; /* Center text horizontally */
        text-decoration: none; /* Remove underline */
        border-radius: 0.5rem; /* Match typical Streamlit button radius */
    }

    /* Hide hamburger menu icon (if desired) */
    /* .st-emotion-cache-1629p8f { 
        display: none !important;
    } */
    </style>
    """, 
    unsafe_allow_html=True
)

st.markdown('<div class="main-header">Forecasters\' Tools <a href="#" class="logout-link">Log Out</a></div>', unsafe_allow_html=True)

# ---

# Main Page Content (Below the Header)
col_left, col_center, col_right = st.columns([1, 2, 1])

with col_center:
    st.markdown("<h3 style='text-align: center; margin-top: 20px;'>Select a Map Tool</h3>", unsafe_allow_html=True)
    st.markdown("---")

    # Use st.page_link to create buttons that navigate to the specific pages
    # NOTE: The path for the page link is relative to the Streamlit run directory,
    # and must match the structure you showed (assuming 'pages/' folder).
    # Since your files are at the root level in the image, I'll use the filename, 
    # but for a multipage app, they should ideally be in a 'pages/' folder.
    
    st.page_link("pages1_Rainfall_Outlook.py", label="Rainfall Outlook ☔", icon="💧")
    st.page_link("pages2_Temperature_Outlook.py", label="Temperature Outlook 🌡️", icon="🔥")

    st.markdown("---")

    # You can keep the informational note if you like
    st.info("The tools above are also available in the Streamlit sidebar menu (on the left).")
